
#ifndef CLUE_H
#define CLUE_H

#define CLUE_INITIAL_TOKEN_ARRAY_SIZE 10
#define CLUE_DEBUG_MODE 0
#define CLUE_INTERACTIVE_MODE_MAX_LINE_LENGTH 120
#define CLUE_INITIAL_SYMBOL_TABLE_CAPACITY 10

#endif

